var BreakFast = [
  {
    id: 1,
    name: "Everyday Pancakes",
    images: ["BF-1.webp"],
    price: 35.92,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 2,
    name: "Waffles",
    images: ["BF-2.webp"],
    price: 38.36,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 3,
    name: "French Toast",
    images: ["BF-3.webp"],
    price: 47.88,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 4,
    name: "Shakshuka With Feta",
    images: ["BF-4.webp"],
    price: 31.95,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 5,
    name: "Avocado Toast",
    images: ["BF-5.webp"],
    price: 43.78,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 6,
    name: "Scallion Egg Wrap",
    images: ["BF-6.webp"],
    price: 31.2,
    type : "BreakFast",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
];

var Lunch = [
  {
    id: 7,
    name: "Bean Quesadillas",
    images: ["L-1.png"],
    price: 30.43,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 8,
    name: "Creamy Mushroom",
    images: ["L-2.png"],
    price: 29.51,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 9,
    name: "Noodle Salad",
    images: ["L-3.png"],
    price: 31.66,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 10,
    name: "Feta Grilled Cheese",
    images: ["L-4.png"],
    price: 42.17,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 11,
    name: "Chicken Pasta",
    images: ["L-5.png"],
    price: 25.22,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 12,
    name: "Sausage Pasta",
    images: ["L-6.png"],
    price: 43.46,
    type : "Lunch",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
];

var Dinner = [
  {
    id: 13,
    name: "Creamy Beans",
    images: ["Di-1.webp"],
    price: 42.85,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 14,
    name: "Classic Shrimp",
    images: ["Di-2.webp"],
    price: 49.42,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 15,
    name: "Kung Pao Chicken",
    images: ["Di-3.webp"],
    price: 28.16,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 16,
    name: "Elena Sandwich",
    images: ["Di-4.webp"],
    price: 29.0,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 17,
    name: "Turmeric Chicken",
    images: ["Di-5.webp"],
    price: 45.23,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 18,
    name: "Original Nachos",
    images: ["Di-6.webp"],
    price: 26.45,
    type : "Dinner",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
];

var Drinks = [
  {
    id: 19,
    name: "Blueberry Lemonade",
    images: ["Dr-1.webp"],
    price: 36.49,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 20,
    name: "Frozen Lemonade",
    images: ["Dr-2.webp"],
    price: 41.5,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 21,
    name: "Raspberry Lemonade",
    images: ["Dr-3.webp"],
    price: 48.14,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 22,
    name: "Raspberry Lemonade",
    images: ["Dr-4.webp"],
    price: 46.99,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 23,
    name: "Honeydew Melon",
    images: ["Dr-5.webp"],
    price: 43.41,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
  {
    id: 24,
    name: "Changing Lemonade",
    images: ["Dr-6.webp"],
    price: 42.42,
    type : "Drinks",
    description: "Lorem ipsum dolor, sit amet consectetur adipisicingelit. Nihil, incidunt.",
  },
];

var allMenu = [
    ...BreakFast, 
    ...Lunch, 
    ...Dinner, 
    ...Drinks
];
